name: create merge pr
description: "create pr with merge between dev branch and given branch"
inputs:
  token:
    required: true
  merge-with-branch:
    required: false
    default: "main"
    description: "the branch you want to merge with"

runs:
  using: "composite"
  steps:
    - id: extract-name-parts
      uses: actions/github-script@v6
      with:
        script: |
          const script = require('./.github/scripts/extract-name-params.js')
          script(core, '${{ github.ref }}');
    - name: output merge branch name
      id: merge-branch
      run: echo "{name}={merge/${{steps.extract-name-parts.outputs.version}}/${{ inputs.merge-with-branch }}}" >> $GITHUB_OUTPUT
      shell: bash
    - name: create merge branch
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        # switch to merge branch from the current (release / hotfix) branch
        git switch -C ${{steps.merge-branch.outputs.name}}
        # merge with input branch (default dev)
        git pull origin ${{ inputs.merge-with-branch }} --ff -X theirs
        git push origin ${{steps.merge-branch.outputs.name}} --force
      shell: bash

    - name: create merge pr
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const script = require('./.github/scripts/open-pr.js')
          await script({ github, context, branchName: '${{steps.merge-branch.outputs.name}}', originBranchName: '${{inputs.merge-with-branch}}' });
