name: bump and publish
description: 'bump patch version of version and publish to npm'
inputs:
  push-token:
    required: true
  npm-token:
    required: true
  branch-name:
    required: false
    default: ${{ github.ref }}
  should-create:
    required: false
    default: false

outputs:
  published-version:
    description: the new npm version
    value: ${{ steps.package-version.outputs.full_version }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install --frozen-lockfile 
      shell: bash
    - name: setup git config 
      shell: bash
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        echo ${{ github.actor }}
    - name: create branch
      if: ${{ inputs.should-create }} 
      shell: bash
      run: git checkout -b ${{ inputs.branch-name }}
    - name: bump version 
      shell: bash
      run: |
        npm version patch -m "bump version %s"
        yarn build
    
    - run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.push-token }}
        branch: ${{ inputs.branch-name }}
        tags: true
    
    - id: package-version
        uses: actions/github-script@v6
        with: 
          script: |
             const script = require('./scripts/extract-version.js')
             script(core);