name: update ng 
description: 'update ng branch with correct react version'
inputs:
  branch-name:
    required: true
  react-version:
    required: true
  token:
    required: true
  should-create:
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'alissaVrk/ng-with-react'
        ref: master
        token: ${{ inputs.token }}
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      shell: bash
    - name: create branch
      if: ${{ inputs.should-create }}
      shell: bash
      run: git checkout -b ${{ inputs.branch-name }}

    - name: update ng react version
      run: |
        git checkout ${{ inputs.branch-name }}
        npm i alissa-todo-react-query@${{ inputs.react-version }}
        git commit -am "bump react version ${{ inputs.branch-name }}"
        git push origin ${{ inputs.branch-name }}
      shell: bash
