name: autorun - bump hotfix version
run-name: bump ${{ github.ref }}

on:
  pull_request:
    types:
      - closed
    branches:
      - "hotfix/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      ng-version: ${{ steps.extract-name-parts.outputs.ngVersion }}
      published-version: ${{ steps.bump-and-publish.outputs.published-version }}
      release-branches: ${{ steps.find-release-branches.outputs.release_branches }}
    steps:
      - name: checkout hotfix branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: extract name parts
        id: extract-name-parts
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/extract-name-params.js')
            script(core, '${{ github.ref }}');
      - name: bump version and publish to npm
        id: bump-and-publish
        uses: ./.github/actions/bump-and-publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - name: find all release branches
        id: find-release-branches
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/find-release-branches-and-dev.js')
            script(github, core);

  create-merge-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    strategy:
      matrix:
        branch: ${{ needs.react.outputs.release-branches }}
    steps:
      - name: checkout react for actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: create merge pr to dev
        uses: ./.github/actions/create-merge-pr
        with:
          token: ${{ github.token }}
          merge-with-branch: ${{ matrix.branch }}

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - name: checkout react for actions
        uses: actions/checkout@v3
      - name: update react version in ng hotfix release branch
        uses: ./.github/actions/update-ng-branch
        with:
          branch-name: release/${{ needs.react.outputs.ng-version }}
          react-version: ${{ needs.react.outputs.published-version }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      #here we could, in theory, deploy to jenkins the new feature branch
