name: autorun - bump release version

on:
  pull_request:
    types:
      - closed
    branches:
      - "release/**"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version-name: ${{ steps.extract-name-parts.outputs.version }}
      branch-desc: ${{ steps.extract-name-parts.outputs.desc }}
      published-version: ${{ steps.bump-and-publish.outputs.published-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - id: extract-name-parts
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/extract-name-params.js')
            script(core, '${{ github.ref }}');
      - id: bump-and-publish
        uses: ./.github/actions/bump-and-publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/create-merge-pr
        with:
          token: ${{ github.token }}

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/update-ng-branch
        with:
          branch-name: feature/rt${{ needs.react.outputs.version-name }}/${{ needs.react.outputs.branch-desc }}
          react-version: ${{ needs.react.outputs.published-version }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      #here we could, in theory, deploy to jenkins the new feature branch
