name: create hotfix

on: 
  workflow_dispatch: 
    inputs: 
      name: 
        description: 'suffix for the branch names'
        required: true
        type: string
      ng-version: 
        description: 'ng hotfix version to be created'
        required: true
        type: string

jobs:
  react:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.full_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - id: package-version
        uses: actions/github-script@v6
        with: 
          script: |
             const script = require('./.github/scripts/extract-version.js')
             script(core);
      - id: branch-name
        run: echo "::set-output name=name::hotfix/${{ steps.package-version.outputs.full_version}}/${{inputs.ng-version}}/${{inputs.name}}"
      - name: create hotfix
        run: |
          git checkout -b ${{ steps.branch-name.outputs.name }}
          git push origin ${{ steps.branch-name.outputs.name }}

  ng:
    runs-on: ubuntu-latest
    needs: react
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'alissaVrk/ng-with-react'
          ref: 'master'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: create ng branch for hotfix
        run: |
          git checkout -b release/${{inputs.ng-version}}
          git push origin release/${{inputs.ng-version}}
      - run: echo ng branch created release/${{inputs.ng-version}}

