name: merge to prod
on: 
  workflow_dispatch
concurrency: prod

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout prod
          git pull origin ${{ github.ref }} --ff
          git push origin prod
          git push origin --delete ${{ github.ref }}

