name: publish release

on: 
  pull_request: 
    types:
      - closed
    branches: 
      - 'release/**'

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-name-parts.outputs.version }}
      branch-desc: ${{ steps.extract-name-parts.outputs.desc }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: extract-name-parts
        uses: actions/github-script@v6
        with: 
          script: |
             const script = require('./scripts/extract-name-params.js')
             script(core, '${{ github.ref }}');
      - uses: ./.github/actions/bump-and-publish
      - uses: ./.github/actions/create-merge-pr

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/update-ng-branch
        with: 
          branch-name: feature/rt${{ needs.react.outputs.version }}/${{ needs.react.outputs.branch-desc }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      #here we could, in theory, deploy to jenkins the new feature branch

