name: publish hotfix

on: 
  pull_request: 
    types:
      - closed
    branches: 
      - 'hotfix/**'

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      ng-version: ${{ steps.extract-name-parts.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - id: extract-name-parts
        run: node scripts/extract-name-params.js
        env:
          branch: ${{ github.ref }} 
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: bump version
        run: |
          npm version patch -m "bump version %s"
          yarn build
          git push origin ${{ github.ref }} --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # TODO: this should work with a PR - so build will run
      - run: |
        git checkout main
        git pull origin main --ff
      - id: dev-version
        run: node scripts/extract-version.js
      - run: |
        git merge ${{ github.ref }} --ff
        npm version ${{ steps.dev-version.outputs.full_version }}
        git push origin main

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - id: branch-name
        run: echo "::set-output name=name::release/${{ needs.react.outputs.ng-version }}"
      - uses: actions/checkout@v3
        with:
          repository: 'alissaVrk/ng-with-react'
          ref: ${{ steps.branch-name.outputs.name }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: update ng react version
        run: |
          npm i alissa-todo-react-query
          git commit -am "bump react version"
          git push origin ${{ steps.branch-name.outputs.name }}
      #here we could, in theory, deploy to jenkins the new feature branch

