name: publish hotfix

on: 
  pull_request: 
    types:
      - closed
    branches: 
      - 'hotfix/**'
      
concurrency: ${{ github.ref }}

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      ng-version: ${{ steps.extract-name-parts.outputs.ngVersion }}
      published-version: ${{ steps.bump-and-publish.outputs.published-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: extract-name-parts
        uses: actions/github-script@v6
        with: 
          script: |
             const script = require('./scripts/extract-name-params.js')
             script(core, '${{ github.ref }}');
      - id: bump-and-publish
        uses: ./.github/actions/bump-and-publish
        with:
          push-token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/create-merge-pr

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/update-ng-branch
        with: 
          branch-name: release/${{ needs.react.outputs.ng-version }}
          react-version: ${{ needs.react.outputs.published-version }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      #here we could, in theory, deploy to jenkins the new feature branch

