name: publish release

on: 
  pull_request: 
    types:
      - closed
    branches: 
      - 'release/**'

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-name-parts.outputs.version }}
      branch-desc: ${{ steps.extract-name-parts.outputs.desc }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - id: extract-name-parts
        run: node scripts/extract-name-params.js
        env:
          branch: ${{ github.ref }} 
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: bump version
        run: |
          npm version patch -m "bump version %s"
          yarn build
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: create merge branch
        run: |
          git switch -C merge/${{steps.extract-name-parts.outputs.version}}
          git pull origin main --ff -X theirs
          git push origin merge/${{steps.extract-name-parts.outputs.version}} --force
      - uses: actions/github-script@v6
        with: 
          script: |
             const script = require('./scripts/open-pr.js')
             await script({ github, context, brancName: merge/${{steps.extract-name-parts.outputs.version}} });

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - id: branch-name
        run: echo "::set-output name=name::feature/rt${{ needs.react.outputs.version }}/${{ needs.react.outputs.branch-desc }}"
      - uses: actions/checkout@v3
        with:
          repository: 'alissaVrk/ng-with-react'
          ref: ${{ steps.branch-name.outputs.name }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: update ng react version
        run: |
          npm i alissa-todo-react-query
          git commit -am "bump react version"
          git push origin ${{ steps.branch-name.outputs.name }}
      #here we could, in theory, deploy to jenkins the new feature branch

