name: publish release

on: 
  pull_request: 
    types:
      - closed
    branches: 
      - 'release/**'

jobs:
  react:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-name-parts.outputs.result.version }}
      branch-desc: ${{ steps.extract-name-parts.outputs.result.desc }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - id: extract-name-parts
        uses: actions/github-script@v6
        with: 
          script: |
             const script = require('./scripts/extract-name-params.js')
             await script('${{ github.ref }}');
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo ${{ github.actor }}
      - name: bump version
        run: |
          npm version patch -m "bump version %s"
          yarn build
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/create-merge-pr

  ng:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: react
    steps:
      - uses: ./.github/actions/update-ng-branch
        with: 
          branch-name: feature/rt${{ needs.react.outputs.version }}/${{ needs.react.outputs.branch-desc }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      #here we could, in theory, deploy to jenkins the new feature branch

